### ISSUE TITLE
implement the `plugin://` scheme for VScode/LSP

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/rascal-language-servers#110]
The `plugin` scheme is a core scheme in the Rascal run-time which allows an IDE or other run-time environment to resolve libraries via their own plugin mechanism instead of the JVM classpath.

For Eclipse, the `plugin` scheme resolves to OSGI Bundles, for example.

When some project depends in `Require-Libraries` on `lib://<libName>` then the implementation of the `lib` scheme always checks if there is not a `plugin` available to implement this library. If not, then it defaults to the current JVM classpath and looks for RASCAL.MF files there with the right `Project-Name` setting. Otherwise, `lib://<libName>/<anything>` resolves to `plugin://<libName>/<anything>` from there on.

Plugin schemes are important for _injecting_ dependencies; something which the JVM classpath does not offer. For example, when starting a second level Eclipse or VScode, new extension/plugins contribute new languages to an existing LSP on already running JVM, with its fixed classpath. This is the reason that `lib://` offers the feature of being a `facade` for `plugin://`

The current proposal is to add `plugin` as a `ISourceLocationInputResolver` (not a `ILogicalSourceLocationResolver` because that won't fly with the `lib` scheme which resolves all permanent locations it is a facade for at class loading time).

Caveats:
* deadlocks can be expected if we communicate requests for path resolution dynamically over the LSP. We have that experience with the `project://` scheme at least. So we communicate all project locations to the LSP server at start-up time.
* if we may depend on a single root folder for all extensions, and extension folders are named after the extension name, then that would be great. All we need is this information at boot time and we can resolve our own extension/plugin folders from there.
* if this is _not_ the case, then we need something more elaborate where we communicate the location of all extensions and their names at boot time, and we have to restart the LSP if extensions are added or removed.
* the `lib://` facade mechanism was implemented against the example of `plugin://` for the Eclipse OSGI situation. This more general usage might ask for generalizations or enhancements in the `rascal` project where this scheme is implemented.

**Comment by DavyLandman** [comment]
@jurgenvinju this is deprecated right?

**Comment by jurgenvinju** [comment]
Let's see if we can do without this for the time being. The current plan is to slowly move away from the `lib://` scheme with the following idea:
* RASCAL.MF will only name the library dependencies by string name, not by URI
* Or/And: Require-Libraries will dissappear completely as  feature
* Replaced by the dependencies of pom.xml
* And a new library scheme will unambiguously define the location of a `mvn` jar like so: `mvn://package-id/project-#VERSION-CONSTRAINT` 
* The project configuratiojn code that _produces_ pathConfig instances will create the `mvn` URIs.
* The mvn URI resolver will look in the .m2 cache and otherwise try to use mvn to download the artefacts, or otherwise throw IO exceptions.
* Even though `mvn` URIs are also not universal (dependent on the repositories configuration in the local pom.xml), at least they are precise _and_ they are deterministic. As long as projects do not move between different repo's they are reasonable.

That's the plan. So we can deprecated this.
