### ISSUE TITLE
Show progress bar in UI when generating evaluators & parsers for parametric DSL.

### ISSUE THREAD

**Issue by DavyLandman** [usethesource/rascal-language-servers#118]
The first opened file gets no feedback in the UI that something is happening.

While in the background we are starting the evaluator, and importing the main module (generating the parser) and calling the main function.

Since we know this is often a slow task, we should open up a progressbar for this initialization case.

Note that the java IDE does something similar when loading the active projects at startup.

**Comment by DavyLandman** [comment]
The java IDE does something similar when loading the active projects at startup.

**Comment by jurgenvinju** [comment]
related to #81 ?

**Comment by DavyLandman** [comment]
Yes, that's good enough. At some point we might consider making it more visible. But good for now, there is a place that reports stuff is happening.
