### ISSUE TITLE
Cannot create rascal terminal if no files are open

### ISSUE THREAD

**Issue by DavyLandman** [usethesource/rascal-language-servers#121]
If you use the command window to open a rascal terminal, nothing happens, and this is printed to the extension log:

```
[2021-12-20 17:18:36.256] [exthost] [warning] Cannot execute rascalmpl.createTerminal because there is no active text editor.
```

**Comment by rodinaarssen** [comment]
In addition: if you have a file open belonging to a project having no RASCAL.MF, nothing at all happens (no log entries either).

We currently "miss" the old Eclipse behavior where a terminal would be opened with project `null`
