### ISSUE TITLE
Rascal summary broken

### ISSUE THREAD

**Issue by rodinaarssen** [usethesource/rascal-language-servers#126]
use/def and hovering is broken after the java11 merge. Check whether it's fixed after https://github.com/usethesource/rascal-core/pull/10

**Comment by rodinaarssen** [comment]
Still broken

**Comment by DavyLandman** [comment]
@rodinaarssen I think you've reported that it's not broken anymore?

**Comment by rodinaarssen** [comment]
Indeed, this has been fixed now that tpl files are found again. The version on the marketplace does not yet contain this, though
