### ISSUE TITLE
Require-Libraries dependencies broken for open projects

### ISSUE THREAD

**Issue by rodinaarssen** [usethesource/rascal-language-servers#127]
In VSCode, no full project build is triggered when a file is saved. Therefore, no `RASCAL.MF` is present in `target/classes/META-INF`, no `.tpl` files are found, the lib-to-project translation fails, and the dependee is not added to the depender's PathConfig.

**Comment by rodinaarssen** [comment]
It's also broken for open projects that *do* have `.tpl` files in `target/classes/rascal`

**Comment by jurgenvinju** [comment]
Do these projects have a RASCAL.MF file in the target folder?

**Comment by rodinaarssen** [comment]
Yes, `target/classes/META-INF/RASCAL.MF`

**Comment by jurgenvinju** [comment]
Let's see if that fix actually resolves the problem.

**Comment by rodinaarssen** [comment]
It does! Thanks a lot, @jurgenvinju
