### ISSUE TITLE
New 0.2.0 release that includes java 11 and newer typechecker

### ISSUE THREAD

**Issue by DavyLandman** [usethesource/rascal-language-servers#142]
Create a new release that switches to java 11

- [x] Write release notes
- [x] Test functionality
   - [x] Rascal
   - [x] DSL
- [x] release rascal-lsp
- [x] release rascal-vscode-extension

**Comment by rodinaarssen** [comment]
Rascal:
* Syntax highlighting
* Outline
* Use/def: local file
* Use/def: into other open project
* Use/def: into standard library
Parametric:
* Register language
* Syntax hightlighting
* Outline
* Use/def

**Comment by DavyLandman** [comment]
Thanks @rodinaarssen for helping test the new version. I've just release v0.2.0: a822939bc2434c92531b3810abf5fa6e47006248
