### ISSUE TITLE
How-to: Binding to Java classes using local jars?

### ISSUE THREAD

**Issue by aukeroorda** [usethesource/rascal-language-servers#156]
**Context**
Hi - I'm trying to move a Rascal-eclipse project to Rascal-lsp. The Rascal-eclipse project uses multiple jars to provide certain functionality to the language implemented. I was not sure how to set up the Java bindings in this new environment, as Vallang was not available, but I learned that this could be done by using Maven. I initialized a new Maven project, and added the usethesource Maven repository and Vallang dependency, and this works. However one of my dependencies is not available on a Maven repository; there is only a jar available, and I am struggling to get it working with Rascal in the VScode environment; I keep on running into the following error.

**To Reproduce**

This requires a Rascal project in which Java bindings are used and a local jar. A minimal one, including a local jar, is available at [this skeleton repo](https://github.com/aukeroorda/rascal-lsp-skeletons.git) at the branch `local-java-libs`. To directly clone this branch:
```
git clone -b local-java-libs https://github.com/aukeroorda/rascal-lsp-skeletons.git
```
My inexperience with Maven may be the cause of the problems here, so I've included the actions I do with maven in the reproduction steps as well.

**Steps to reproduce the behavior**:
1. First, install the provided jar into a local maven repository. In `rascal-lsp-skeletons/my-app`:
```
mvn install:install-file \
  -DlocalRepositoryPath=local-maven-repo \
  -Durl=file:./local-maven-repo/ \
  -DrepositoryId=local-maven-repo \
  -DcreateChecksum=true \
  -DupdateReleaseInfo=true \
  -DgeneratePom=true \
  -Dpackaging=jar \
  -Dfile=./lib/frink.jar \
  -DgroupId=frinklang \
  -DartifactId=frink \
  -Dversion=22.4.18
```

2. Let Maven download the other dependencies: `mvn verify`. The `frink` artifact is already added as a dependency in `pom.xml`.
3. Open the `my-app` project in VScode: `code .`
4. Open the file `my-app/src/RascalJavaBindings.rsc` and click "Import in new Rascal terminal".
5. In the new Rascal terminal, see the error

**Expected behavior**
For Rascal to import the RascalJavaBindings module, and make available the function that is defined in it. 

**Stack traces**
<details><summary>Stack trace after `import RascalJavaBindings.rsc` into the Rascal terminal</summary>

```
INFO: detected |lib://rascal-lsp| at |jar+file:///Users/auke/.vscode/extensions/usethesource.rascalmpl-0.2.0/assets/jars/rascal-lsp.jar!/|
INFO: detected |lib://rascal| at |jar+file:///Users/auke/.vscode/extensions/usethesource.rascalmpl-0.2.0/assets/jars/rascal.jar!/|
INFO: resolved |lib://rascal-lsp| at |jar+file:///Users/auke/.vscode/extensions/usethesource.rascalmpl-0.2.0/assets/jars/rascal-lsp.jar!/|
WARNING: could not resolve dependency on: |lib://frink| because it does not seem to exist as a project or a library.
WARNING: could not resolve dependency on: |lib://frinklang| because it does not seem to exist as a project or a library.
WARNING: could not resolve dependency on: |lib://local-maven-repo| because it does not seem to exist as a project or a library.
WARNING: could not resolve dependency on: |file:///local-maven-repo| because it does not seem to exist as a project or a library.
Rascal Version: 0.22.1
Rascal-lsp Version: 2.0.1-SNAPSHOT
pathConfig(
  javaCompilerPath=[
    |file:///Users/auke/.vscode/extensions/usethesource.rascalmpl-0.2.0/assets/jars/rascal-lsp.jar|,
    |file:///Users/auke/.vscode/extensions/usethesource.rascalmpl-0.2.0/assets/jars/rascal.jar|
  ],
  bin=|target://my-app|,
  classloaders=[
    |lib://rascal-lsp|,
    |target://my-app|,
    |system:///|
  ],
  libs=[|lib://rascal|],
  srcs=[
    |lib://rascal-lsp|,
    |file:///Users/auke/rascal-lsp-skeletons/my-app/src|
  ],
  courses=[])INFO: resolved |lib://rascal| at |jar+file:///Users/auke/.vscode/extensions/usethesource.rascalmpl-0.2.0/assets/jars/rascal.jar!/|
rascal>import RascalJavaBindings;
org.rascalmpl.exceptions.JavaMethodLink: Cannot link method com.mycompany.app.App because: null
        at org.rascalmpl.interpreter.utils.JavaBridge.getJavaClassInstance(JavaBridge.java:426)
        at org.rascalmpl.interpreter.result.JavaMethod.<init>(JavaMethod.java:95)
        at org.rascalmpl.interpreter.result.JavaMethod.<init>(JavaMethod.java:52)
        at org.rascalmpl.semantics.dynamic.FunctionDeclaration$Abstract.interpret(FunctionDeclaration.java:62)
        at org.rascalmpl.semantics.dynamic.Declaration$Function.interpret(Declaration.java:117)
        at org.rascalmpl.semantics.dynamic.Toplevel$GivenVisibility.interpret(Toplevel.java:35)
        at org.rascalmpl.semantics.dynamic.Module$Default.interpret(Module.java:79)
        at org.rascalmpl.semantics.dynamic.Import.loadModule(Import.java:319)
        at org.rascalmpl.semantics.dynamic.Import.importModule(Import.java:240)
        at org.rascalmpl.semantics.dynamic.Import$Default.interpret(Import.java:206)
        at org.rascalmpl.semantics.dynamic.Command$Import.interpret(Command.java:81)
        at org.rascalmpl.interpreter.Evaluator.eval(Evaluator.java:1106)
        at org.rascalmpl.interpreter.Evaluator.eval(Evaluator.java:976)
        at org.rascalmpl.interpreter.Evaluator.eval(Evaluator.java:931)
        at org.rascalmpl.repl.RascalInterpreterREPL.evalStatement(RascalInterpreterREPL.java:131)
        at org.rascalmpl.repl.BaseRascalREPL.handleInput(BaseRascalREPL.java:106)
        at org.rascalmpl.vscode.lsp.terminal.LSPTerminalREPL$1.handleInput(LSPTerminalREPL.java:192)
        at org.rascalmpl.repl.BaseREPL.handleInput(BaseREPL.java:180)
        at org.rascalmpl.repl.BaseREPL.handleCommandQueue(BaseREPL.java:420)
        at org.rascalmpl.repl.BaseREPL.run(BaseREPL.java:337)
        at org.rascalmpl.vscode.lsp.terminal.LSPTerminalREPL.main(LSPTerminalREPL.java:261)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.rascalmpl.interpreter.utils.JavaBridge.getJavaClassInstance(JavaBridge.java:404)
        ... 20 more
Caused by: java.lang.NoClassDefFoundError: frink/parser/Frink
        at com.mycompany.app.App.<init>(App.java:15)
        ... 25 more
Caused by: java.lang.ClassNotFoundException: frink.parser.Frink
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 26 more
|prompt:///|(0,26,<1,0>,<1,26>): Could not import module RascalJavaBindings: Cannot link method com.mycompany.app.App because: null
Advice: |http://tutor.rascal-mpl.org/Errors/Static/ModuleImport/ModuleImport.html|
ok
rascal>
```
</details>

**Desktop (please complete the following information):**
 - Context: Rascal-lsp plugin as installed from the marketplace.
 - Rascal Version 0.23.1
 - Rascal-lsp Version 2.1.1-SNAPSHOT

**Additional information**
<details><summary>Verifying local jar installation</summary>

How I tried to verify that the installation of the local jar to the local-maven-repo is successful:
1. Purge the local repository of this project:
```
mvn dependency:purge-local-repository
```
Note that this already gives an error regarding the missing artifact `frinklang:frink:jar:22.4.18`. I am _not_ sure what the implications of this are.
2. Next, let maven try to install/resolve the dependencies:
```
mvn verify
```
This results in a build failure, as "The POM for frinklang:frink:jar:22.4.18 is missing, no dependency information available".
3. Execute step 1 of the reproduction.
4. Let Maven try to install/resolve the dependencies again. Note the `-U` flag to force an update:
```
mvn verify -U
```
This succeeds, and therefore I think that the installation of the local jar to the local-maven-repo was successful, and should therefore be available in the Java file used in the Rascal binding.
</details>

<details>
<summary>How I setup a Rascal-lsp project</summary>

For me, it was quite unclear how to get started in VScode with a Rascal project. Therefore I have tried to document the process in the repository [https://github.com/aukeroorda/rascal-lsp-skeletons](https://github.com/aukeroorda/rascal-lsp-skeletons). In [this](https://github.com/aukeroorda/rascal-lsp-skeletons/pull/4) PR you can see an overview of the changes made in an attempt to get the usage of the local jar working.
</details>

**Comment by DavyLandman** [comment]
I don't think we've solved the cross-project java dependencies yet. We have solved maven dependencies, and also rascal cross-project dependencies, but if I'm not mistaken, this one is still on the list. Pinging @jurgenvinju and @rodinaarssen since they've worked on this most recently.

**Comment by jurgenvinju** [comment]
Auke is talking about something outside of the VScode context; right @aukeroorda ? You need to reuse part of the rascal-lsp, but not the VScode editor per se? Just checking.

The trick to making Rascal and Java code available to a client project is all in the construction of the JVM's classpath. That's the `-cp` parameter to `java[.exe]` The VScode IDE uses this code to make that work: https://github.com/usethesource/rascal-language-servers/blob/d7943685d5529206f12f7d170733919a2b26507d/rascal-vscode-extension/src/extension.ts#L299 It uses internal knowledge of where the jar files are installed in the extension, and adds the target folder of the current project to the classpath as well. 

The above is necessary for all the standard code that the Rascal interpreter needs to run itself. But then there is the code that is run by "java" functions in Rascal. For this Rascal uses its own dynamic classloader called the `JavaBridge`. It works by reading the RASCAL.MF file at start-up time (so when the LSP or a terminal start) and constructs a classpath by actually running `mvn dependency:classpath` to configure the classloader. It's a complex situation, since classloaders can also come from plugin mechanisms such as OSGI and other loading mechnisms. However, you can read the input to the loader mechanism by calling `util::Reflective::getProjectPathConfig` on your current project `|project://myProject|`. The right jar files should be listed under `.classloaders`. 

Please let us know how far you got. Unfortunately, I'll be camping the next 2 weeks.

**Comment by tvdstorm** [comment]
Just to clarify (perhaps): the problem here is binding Rascal code to Java code that is located in a plain jar (and not on some Maven repo), in the context of VSCode (both DSL-IDE and Terminal). I would expect that installing the jar into a local/filesystem Maven repo, and then declaring a dependency in pom.xml would do the trick, but apparently not.

**Comment by aukeroorda** [comment]
>> jurgenvinju: Auke is talking about something outside of the VScode context; right @aukeroorda ? You need to reuse part of the rascal-lsp, but not the VScode editor per se? Just checking.

> tvdstorm: Just to clarify (perhaps): the problem here is binding Rascal code to Java code that is located in a plain jar (and not on some Maven repo), in the context of VSCode (both DSL-IDE and Terminal). I would expect that installing the jar into a local/filesystem Maven repo, and then declaring a dependency in pom.xml would do the trick, but apparently not.

This is indeed the scenario. I am not sure if this answers the question "You need to reuse part of the rascal-lsp, but not the VScode editor per se?" though. For this I am too unfamiliar with the structure of rascal-lsp in vscode.

**ProjectPathConfig**
> However, you can read the input to the loader mechanism by calling `util::Reflective::getProjectPathConfig` on your current project `|project://myProject|`. The right jar files should be listed under `.classloaders`.
This is the output that I get. Unfortunately, there is no direct path to the required Jar, nor to one of the close parent directories. 
```rascal
rascal>getProjectPathConfig(|project://my-app|);
WARNING: could not resolve dependency on: |lib://frink| because it does not seem to exist as a project or a library.
WARNING: could not resolve dependency on: |lib://frinklang| because it does not seem to exist as a project or a library.
WARNING: could not resolve dependency on: |lib://local-maven-repo| because it does not seem to exist as a project or a library.
WARNING: could not resolve dependency on: |file:///local-maven-repo| because it does not seem to exist as a project or a library.
PathConfig: pathConfig(
  javaCompilerPath=[
    |file:///Users/auke/.vscode/extensions/usethesource.rascalmpl-0.2.1/assets/jars/rascal-lsp.jar|,
    |file:///Users/auke/.vscode/extensions/usethesource.rascalmpl-0.2.1/assets/jars/rascal.jar|
  ],
  bin=|target://my-app|,
  classloaders=[
    |lib://rascal-lsp|,
    |target://my-app|,
    |system:///|
  ],
  libs=[
    |lib://rascal|,
    |lib://rascal-lsp|
  ],
  srcs=[|project://my-app/src|],
  courses=[])
```

I had tried to add the library to the `RASCAL.MF` file, under `Require-Libraries` in multiple random ways; this is the reason for the 4 unresolved dependencies at the start:
```
Require-Libraries: |lib://rascal-lsp|, |lib://frink|, |lib://frinklang|, |lib://local-maven-repo|, |file:///local-maven-repo|
```

**mvn dependency:classpath**
The output of `mvn dependency:classpath` somewhat surprised me, as I see no reference to the `local-maven-repo` I installed the `frink.jar` file in. Here is the output, with a newline after each path:
```
/Users/auke/.m2/repository/junit/junit/4.11/junit-4.11.jar:
/Users/auke/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:
/Users/auke/.m2/repository/io/usethesource/vallang/0.14.4/vallang-0.14.4.jar:
/Users/auke/.m2/repository/io/usethesource/capsule/0.7.0/capsule-0.7.0.jar:
/Users/auke/.m2/repository/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar:
/Users/auke/.m2/repository/org/tukaani/xz/1.9/xz-1.9.jar:
/Users/auke/.m2/repository/com/github/luben/zstd-jni/1.5.1-1/zstd-jni-1.5.1-1.jar:
/Users/auke/.m2/repository/com/github/ben-manes/caffeine/caffeine/3.0.4/caffeine-3.0.4.jar:
/Users/auke/.m2/repository/com/google/errorprone/error_prone_annotations/2.9.0/error_prone_annotations-2.9.0.jar:
/Users/auke/.m2/repository/org/checkerframework/checker-qual/3.21.0/checker-qual-3.21.0.jar:
/Users/auke/.m2/repository/frinklang/frink/22.4.18/frink-22.4.18.jar
```

And these are the contents of `~/.m2/repository/frinklang`:
```
> tree .m2/repository/frinklang
.m2/repository/frinklang
└── frink
    ├── 22.4.18
    │   ├── _remote.repositories
    │   ├── frink-22.4.18.jar
    │   ├── frink-22.4.18.jar.lastUpdated
    │   ├── frink-22.4.18.jar.sha1
    │   ├── frink-22.4.18.pom
    │   ├── frink-22.4.18.pom.lastUpdated
    │   └── frink-22.4.18.pom.sha1
    ├── maven-metadata-local-maven-repo.xml
    └── resolver-status.properties
```

**Comment by jurgenvinju** [comment]
Aha. something is going wrong here indeed! 

* `|lib://frink|, |lib://frinklang|, |lib://local-maven-repo|` all do not work because those jars are not on the JVM classpath when the shell starts. This seems a deep issue with the way Rascal resolves its paths in the VScode context. @rodinaarssen check here: good to know.
* Instead of the `lib:///` paths you could use the absolute `file:///` paths in `Required-Libraries` as a workaround. I'm hoping that should help you go ahead while you wait for a solution from us.

**Comment by aukeroorda** [comment]
Replaced the non-working `lib` declarations in `RASCAL.MF` with:
```
Require-Libraries: |file:////Users/auke/rascal-lsp-skeletons/my-app/local-maven-repo/frinklang/frink/22.4.18/frink-22.4.18.jar|
```
And this does indeed work! Very nice to have this working, as it enables me to finally move away from Eclipse to VScode!

**Comment by jurgenvinju** [comment]
The core issue is that `lib` scheme is resolved "statically" during the construction of the URIResolverRegistry singleton instance. This has beneficial properties, since lazy class loading happens in the JVM and especially in the OSGI context, we may run into race conditions.

However, this makes the `lib` scheme very inflexible. It can not resolve to targets which are resolved after a JVM has started (or after the initial loading of the URIResolverRegistry).

A more dynamic redesign of this: https://github.com/usethesource/rascal/blob/main/src/org/rascalmpl/uri/libraries/RascalLibraryURIResolver.java

may resolve this, but it's not so easy. Have to think about caching and clearing caches for efficiency's sake. Have to think about race conditions. etc.

**Comment by aukeroorda** [comment]
One follow-up question:
Instead of providing a full absolute path:
```path
Require-Libraries: |file:////Users/auke/rascal-lsp-skeletons/my-app/local-maven-repo/frinklang/frink/22.4.18/frink-22.4.18.jar|
```
would it possible to provide a relative path, such that a different location of the project itself does not invalidate the path? I tried a few, but it seems like there isn't at the moment, as none of these work:
```
Require-Libraries: |file:///rascal-lsp-skeletons/my-app/local-maven-repo/frinklang/frink/22.4.18/frink-22.4.18.jar|
Require-Libraries: |file:///my-app/local-maven-repo/frinklang/frink/22.4.18/frink-22.4.18.jar|
Require-Libraries: |file:///local-maven-repo/frinklang/frink/22.4.18/frink-22.4.18.jar|
```

**Comment by jurgenvinju** [comment]
No relative paths do not work, but maybe `home` will work like so: `home:///rascal-lsp-skeletons/...`

**Comment by jurgenvinju** [comment]
question: it could be that using `~/.m2` as local maven repo instead of `~/local-maven-repo` has a positive effect on things. I'm just calling `mvn dependency:build-classpath` without any other options so if the local mvn repo is to be configured it can not find it.

**Comment by aukeroorda** [comment]
> No relative paths do not work, but maybe `home` will work like so: `home:///rascal-lsp-skeletons/...`

This unfortunately only adds it to the `.srcs` section:
```rascal
pathConfig(
  javaCompilerPath=[
    |file:///Users/auke/.vscode/extensions/usethesource.rascalmpl-0.2.1/assets/jars/rascal-lsp.jar|,
    |file:///Users/auke/.vscode/extensions/usethesource.rascalmpl-0.2.1/assets/jars/rascal.jar|
  ],
  bin=|target://my-app|,
  classloaders=[
    |target://my-app|,
    |system:///|
  ],
  libs=[|lib://rascal|],
  srcs=[
    |home:///rascal-lsp-skeletons/my-app/local-maven-repo/frinklang/frink/22.4.18/frink-22.4.18.jar|,
    |file:///Users/auke/rascal-lsp-skeletons/my-app/src|
  ],
  courses=[])
```

> question: it could be that using ~/.m2 as local maven repo instead of ~/local-maven-repo has a positive effect on things.
Will give this a try! I've left a trail of attempts in the way to a solution here, and some might indeed be more destructive than helpful.

**Comment by aukeroorda** [comment]
Hmm, okay, so first undo the installation to `local-maven-repo` and re-install in the default location `~/.m2`:
1. `mvn dependency:purge-local-repository` to clean out the installed dependencies
2. Install the local jar without constructing a `local-maven-repo` in the project repository:
```sh
mvn install:install-file \
  -DcreateChecksum=true \
  -DupdateReleaseInfo=true \
  -DgeneratePom=true \
  -Dpackaging=jar \
  -Dfile=./lib/frink.jar \
  -DgroupId=frinklang \
  -DartifactId=frink \
  -Dversion=22.4.18
```
3. `mvn verify`

This installs the jar to `/Users/auke/.m2/repository/frinklang/frink/22.4.18/frink-22.4.18.jar`. All good so far!
Then, in `RASCAL.MF`, update the Require-Libraries path to new location:
```manifest
Require-Libraries: |file:////Users/auke/.m2/repository/frinklang/frink/22.4.18/frink-22.4.18.jar|
```
And this again works! However, replacing this by `|lib://frink/|` or removing it does not work. 

One thing that somewhat confused me is the "summary" of the exception that prevented importing the Rascal file I'm using for the binding, when the required library is not found:
```
org.rascalmpl.exceptions.JavaMethodLink: Cannot link method com.mycompany.app.App because: frink/errors/FrinkEvaluationException
        at org.rascalmpl.interpreter.utils.JavaBridge.getJavaClassInstance(JavaBridge.java:414)
        at org.rascalmpl.interpreter.result.JavaMethod.<init>(JavaMethod.java:95)
        at org.rascalmpl.interpreter.result.JavaMethod.<init>(JavaMethod.java:52)
        at org.rascalmpl.semantics.dynamic.FunctionDeclaration$Abstract.interpret(FunctionDeclaration.java:61)
        at org.rascalmpl.semantics.dynamic.Declaration$Function.interpret(Declaration.java:117)
        at org.rascalmpl.semantics.dynamic.Toplevel$GivenVisibility.interpret(Toplevel.java:35)
        at org.rascalmpl.semantics.dynamic.Module$Default.interpret(Module.java:79)
        at org.rascalmpl.semantics.dynamic.Import.loadModule(Import.java:319)
        at org.rascalmpl.semantics.dynamic.Import.importModule(Import.java:240)
        at org.rascalmpl.semantics.dynamic.Import$Default.interpret(Import.java:206)
        at org.rascalmpl.semantics.dynamic.Command$Import.interpret(Command.java:81)
        at org.rascalmpl.interpreter.Evaluator.eval(Evaluator.java:1106)
        at org.rascalmpl.interpreter.Evaluator.eval(Evaluator.java:976)
        at org.rascalmpl.interpreter.Evaluator.eval(Evaluator.java:931)
        at org.rascalmpl.repl.RascalInterpreterREPL.evalStatement(RascalInterpreterREPL.java:131)
        at org.rascalmpl.repl.BaseRascalREPL.handleInput(BaseRascalREPL.java:106)
        at org.rascalmpl.vscode.lsp.terminal.LSPTerminalREPL$1.handleInput(LSPTerminalREPL.java:192)
        at org.rascalmpl.repl.BaseREPL.handleInput(BaseREPL.java:180)
        at org.rascalmpl.repl.BaseREPL.handleCommandQueue(BaseREPL.java:420)
        at org.rascalmpl.repl.BaseREPL.run(BaseREPL.java:337)
        at org.rascalmpl.vscode.lsp.terminal.LSPTerminalREPL.main(LSPTerminalREPL.java:261)
Caused by: java.lang.NoClassDefFoundError: frink/errors/FrinkEvaluationException
        at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
        at java.base/java.lang.Class.getConstructors(Class.java:1943)
        at org.rascalmpl.interpreter.utils.JavaBridge.getJavaClassInstance(JavaBridge.java:345)
        ... 20 more
Caused by: java.lang.ClassNotFoundException: frink.errors.FrinkEvaluationException
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 24 more
|prompt:///|(0,26,<1,0>,<1,26>): Could not import module RascalJavaBindings: Cannot link method com.mycompany.app.App because: frink/errors/FrinkEvaluationException
Advice: |http://tutor.rascal-mpl.org/Errors/Static/ModuleImport/ModuleImport.html|
```
The summaries state `Cannot link method com.mycompany.app.App because: frink/errors/FrinkEvaluationException`, which give me the impression that code of the `Frink` library was running and a `FrinkEvaluationException` occurred. However, the stacktrace makes clear that the class `FrinkEvaluationException` cannot be found.

**Comment by jurgenvinju** [comment]
In other words: it could be either and its complex. Java throws NoClassDefFoundErrors when exceptions occur in static initializers, but it could also be the Exception class which is actually not found.

**Comment by jurgenvinju** [comment]
* I think `|lib://frink/|` only works for Rascal libraries that contain `META-INF/RASCAL.MF` files.
* Perhaps it's time we also add references to `mvn` artifacts to that scheme... Have to think about this.

**Comment by aukeroorda** [comment]
> Java throws NoClassDefFoundErrors when exceptions occur in static initializers

Okay 🤯, not what I expected!

> This means that the code to frink is found now, so that's cool.

I have to admit I'm not very familiar with Java and its workings, but I assumed that the ClassNotFoundException was already caused by the first import statement in the Java files. However, swapping the order of these two imports:
```java
import frink.errors.FrinkEvaluationException;
import frink.parser.Frink;
``` 
to
```java
import frink.parser.Frink;
import frink.errors.FrinkEvaluationException;
```
_still_ causes the same exception where it cannot find the `FrinkEvaluationException` class. So, with my limited understanding of Java, I agree that this does indicate that the Frink code is indeed found.

**Comment by jurgenvinju** [comment]
don't worry, after all this you'll be an expert ;-) 

I'm sorry if I can't help you further the coming weeks, but it seems you have a workaround now to move forward right? The current issue can be used to improve the Rascal library setup when the spring holidays are over, and that should also help you make your code more accessible to others.
