### ISSUE TITLE
No more highlighting of source code comments

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/rascal-language-servers#173]
**Describe the bug**

Somehow the Rascal LSP does not offer to highlight the comments and tags anymore.

### Screenshot

<img width="697" alt="image" src="https://user-images.githubusercontent.com/1990295/184652696-b0ebf14f-c7e2-4a0c-94d4-eb14eeefee4e.png">

@rodinaarssen since we have worked last together on the semantic syntax highlighter, I guess we caused this and never noticed? or did something happen in the meantime?

**Comment by jurgenvinju** [comment]
Forget about it. There was a parse error and somehow VScode now highlights the code anyway so I thought there was not a parse error.

**Comment by rodinaarssen** [comment]
There is no semantic highlighting there in your screenshot, it's matching braces/parentheses only, which is a separate feature.
