### ISSUE TITLE
Silently unresolved project name leads to downstream issues

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/rascal-language-servers#184]
**Describe the bug**

* I have the `salix` project checked out in my workspace
* `bin:       |target:///|` is what the summaryProvider prints for the resolved target path for .tpl files
* mayhem comes from that downstream. The first module is simply ignored but all depending modules get "unresolved" imports which also become "unused" imports at the same time.

---

if anybody has a hunch how to work around this issue.. I'd like to demonstrate salix tomorrow.

**Comment by jurgenvinju** [comment]
RASCAL.MF:

```
Manifest-Version: 0.0.1
Source: src
Project-Name: salix
```

**Comment by jurgenvinju** [comment]
```
rascal>getProjectPathConfig(|project://salix|)
PathConfig: pathConfig(
  javaCompilerPath=[
    |file:///Users/jurgenv/.vscode/extensions/usethesource.rascalmpl-0.4.0/assets/jars/rascal-lsp.jar|,
    |file:///Users/jurgenv/.vscode/extensions/usethesource.rascalmpl-0.4.0/assets/jars/rascal.jar|,
    |file:///Users/jurgenv/.m2/repository/net/sourceforge/plantuml/plantuml/8059/plantuml-8059.jar|,
    |file:///Users/jurgenv/.m2/repository/org/rascalmpl/rascal/0.19.4-RC2/rascal-0.19.4-RC2.jar|,
    |file:///Users/jurgenv/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar|,
    |file:///Users/jurgenv/.m2/repository/junit/junit/4.13.1/junit-4.13.1.jar|
  ],
  bin=|target://salix|,
  classloaders=[
    |target://salix|,
    |system:///|,
    |file:///Users/jurgenv/.m2/repository/net/sourceforge/plantuml/plantuml/8059/plantuml-8059.jar|,
    |file:///Users/jurgenv/.m2/repository/org/rascalmpl/rascal/0.19.4-RC2/rascal-0.19.4-RC2.jar|,
    |file:///Users/jurgenv/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar|,
    |file:///Users/jurgenv/.m2/repository/junit/junit/4.13.1/junit-4.13.1.jar|
  ],
  libs=[|lib://rascal|],
  srcs=[|project://salix/src|],
  courses=[])
```

**Comment by DavyLandman** [comment]
It would help if you share which projects you have in your workspace, so we can try and reproduce. The current issue doesn't contain enough information. Or are you storing this for yourself?

**Comment by jurgenvinju** [comment]
I'm building a case slowly. It's very confusing to see what matters and what not. Also I don't have the time now. So please bear with me.

**Comment by DavyLandman** [comment]
okay, thanks, I didn't know it was one of these ;) good luck figuring it out.

**Comment by DavyLandman** [comment]
@jurgenvinju is this still a problem?
