### ISSUE TITLE
release 0.5.0 did not get release notes

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/rascal-language-servers#192]
See the readme on the extension page. Only up to release 0.4.0 is documented.

**Comment by DavyLandman** [comment]
https://github.com/usethesource/rascal-language-servers/commit/7e52b3eab4099f3e8bec97f899d918fca2a19f3c

**Comment by jurgenvinju** [comment]
![image](https://user-images.githubusercontent.com/1990295/195098381-430106c9-5ef4-4f90-90db-0142193e2c4e.png)

**Comment by jurgenvinju** [comment]
maybe a reload will fix this one :-)

**Comment by jurgenvinju** [comment]
![image](https://user-images.githubusercontent.com/1990295/195098778-928ea39c-408c-4d82-9d18-b712acbf5c59.png)
