### ISSUE TITLE
getASTs function taking excessively long to complete due to `project` scheme implementation

### ISSUE THREAD

**Issue by aleandromifsud** [usethesource/rascal-language-servers#196]
**Describe the bug**
I am running the VSCode extension (v0.5.1) with JDK 11 when running the getASTs function with a small project it takes approximately 4 minutes to load the AST. Compared to my colleagues 3 seconds.

I load the AST as such: `list[Declaration] smallSqlAST = getASTs(|project://smallsql0.21_src|);`

I have the corresponding project imported in my VSCode project.
When running htop i realised that a lot of memory is being used by Log4J, please find a screenshot attached
![image](https://user-images.githubusercontent.com/23127859/199198695-538bdee4-0065-477e-8924-954543ae4a96.png)

My setup is as follows:
Hardware Model: Lenovo Legion 5 15ARH05
Memory: 16GB
Processor: AMD Ryzen 7 4800H x 16
OS: Pop!_OS 22.04 LTS
OS Type: 64 bit
Java Version: JDK 11.0.17

**To Reproduce**
1. Import the Main module to a new Rascal Terminal
2. Run the main() function which holds the getASTs function

**Comment by aleandromifsud** [comment]
Could it be a misconfiguration on my end? If you require any further information please let me know, would love to help.

**Comment by DavyLandman** [comment]
try importing `util::FileSystem` and timing the `crawl()` for project scheme and a file based one.

**Comment by aleandromifsud** [comment]
I enabled profiling and got the following output for crawl
![image](https://user-images.githubusercontent.com/23127859/199245253-b2029819-4225-4ff5-a1d4-4a44ba694e28.png)

also used profiling with createM3FromMavenProject
![image](https://user-images.githubusercontent.com/23127859/199245406-4bd6a7f7-011e-473b-a5e4-3e58a8ee90d4.png)

**Comment by teuncm** [comment]
Crazy how this leads to such a drastic runtime increase. I have the same problem (Ubuntu 20.04, using VSCode)

**Comment by DavyLandman** [comment]
> We observed that other students running Linux (Pop!_OS, Ubuntu, Fedora) are facing similar issues. Students running Windows or Mac do not seem to face this issue

this is valuable information, thanks

**Comment by DavyLandman** [comment]
> I enabled profiling and got the following output for crawl, in this case `projLoc = |project://smallsql0.21_src|` ![image](https://user-images.githubusercontent.com/23127859/199245253-b2029819-4225-4ff5-a1d4-4a44ba694e28.png)
> 
> also used profiling with createM3FromMavenProject ![image](https://user-images.githubusercontent.com/23127859/199245406-4bd6a7f7-011e-473b-a5e4-3e58a8ee90d4.png)

can you also share the one for just the file crawl?

**Comment by DavyLandman** [comment]
So if you could collect some windows/linux/mac reports for the following commands:

```rascal
import util::FileSystem;
:set profiling true
crawl(|project://smallsql0.21_src|);
crawl(|home:///uva/.../smallsql0.21_src|);
crawl(|file:///uva/.../smallsql0.21_src|);
```

that would help pinpoint where we need to look.

**Comment by aleandromifsud** [comment]
For Linux:
Project:
![image](https://user-images.githubusercontent.com/23127859/199256979-872f1787-30d0-4a2e-808c-6f29c1c1a828.png)

Home:
![image](https://user-images.githubusercontent.com/23127859/199259193-b56857c3-29df-41cb-ab6b-d5b10649502e.png)

File:
![image](https://user-images.githubusercontent.com/23127859/199257336-52ada416-9e59-403e-8172-5758067efeb4.png)

A colleague will be commenting with the result for windows, will try get a result for Mac soon as well :)

**Comment by lbez0019** [comment]
Windows 11 here @DavyLandman (no slow performance issues from my end btw)
Specs:
- Dell XPS 9305
- i5-1135G7
- 16GB RAM
- OpenJDK 11

Crawl for Project:
<img width="511" alt="image" src="https://user-images.githubusercontent.com/45966194/199257479-25fb1531-c77c-4096-95a0-4b1d838c4948.png">

Crawl for Home:
<img width="595" alt="image" src="https://user-images.githubusercontent.com/45966194/199259488-acc77161-0da0-4dd8-8318-6c8e52fbb1d9.png">

Crawl for File:
<img width="784" alt="image" src="https://user-images.githubusercontent.com/45966194/199257906-058b8a47-94ab-4d0d-b145-3312baa072c2.png">

**Comment by DavyLandman** [comment]
thanks this helps a lot. so something with out translation optimisation is going wrong on linux.

**Comment by aleandromifsud** [comment]
If you require any additional information let us know!

**Comment by DavyLandman** [comment]
Yup, that fixed it. 

if you want, you can download this CI build and install it inside vscode (three dots in the corner of the extension tab -> install from VSIX): https://github.com/usethesource/rascal-language-servers/suites/9070026691/artifacts/419727108

**Comment by DavyLandman** [comment]
Also, feel free to re-open the issue if this build doesn't solve the problem.

**Comment by aleandromifsud** [comment]
I uninstalled my current version of the extension and installed the VSIX version, the time has reduced to 2 minutes now.

I will probably still use the file location for now as 2 minutes is still a substantial amount I think.

**Comment by DavyLandman** [comment]
> I uninstalled my current version of the extension and installed the VSIX version, the time has reduced to 2 minutes now.

For the next time, you can just install over it, and when we release a new version, this CI version will be overwritten as well.

> I will probably still use the file location for now as 2 minutes is still a substantial amount I think.

Hmm, those 2 minutes are strange. On my VM I only saw like a factor 1.5 difference.

**Comment by aleandromifsud** [comment]
here are the new results for crawl vs getASTs, hope this helps
crawl:
![image](https://user-images.githubusercontent.com/23127859/199276616-5a7bf812-0817-4430-a302-3272bf9035c4.png)

getASTs
![image](https://user-images.githubusercontent.com/23127859/199276961-3fa6651e-7b46-45e6-b37a-db7ce5474056.png)

**Comment by DavyLandman** [comment]
Okay, found some more delays, and also some URI unparsing & parsing that was happening way to often. The second one should also remove the performance difference on windows.

@aleandromifsud if this one is done, could you pickup the artifact at the bottom and try out with the vsix? https://github.com/usethesource/rascal-language-servers/actions/runs/3371060095

**Comment by jurgenvinju** [comment]
* some reservations about https://github.com/usethesource/rascal-language-servers/commit/4dda94288fb927cd9ceb2beab4d75938312e0ccb 
   * is this really a noticable bottleneck?
   * we need query, fragment, offset, length, start and end line/column information in general on that parameter

**Comment by aleandromifsud** [comment]
Here are the values with the linked vsix extension 
getASTs
![image](https://user-images.githubusercontent.com/23127859/199292675-eb026b2f-b909-4658-a8d2-a2e017a98c6d.png)

crawl:
![image](https://user-images.githubusercontent.com/23127859/199292853-d2ea3e3b-66c1-4181-a27b-a9638e543fa3.png)

**Comment by DavyLandman** [comment]
>   * is this really a noticable bottleneck?
In the Java profile, almost all time was spent in StandardTextReader (and a bit in StandardTextWriter). After this change on windows and Linux the different between the crawl is quite minimal (used to be factor of 2 or 3, now maybe 1.2)

>   * we need query, fragment, offset, length, start and end line/column information in general on that parameter
That parameter was only used inside that single class, for that specific api. I understand your concern, so maybe we should do something more generic, but I did check if this class was used outside of the scope of resolving project paths. (Offsets etc are always dropped for this operation)

**Comment by DavyLandman** [comment]
On linux:

```
rascal>crawl(|file:///tmp/smallsql/|);
FRAMES PROFILE: 10 data points, 27 ticks, tick = 1 milliSecs
  Scope   Ticks        %  Source
  crawl      20    74.1%  |std:///util/FileSystem.rsc|(408,90,<17,0>,<17,90>)
$shell$       5    18.5%  |main://$shell$|
$shell$       2     7.4%  |prompt:///|(4,31,<1,4>,<1,35>)

ASTS PROFILE: 10 data points, 27 ticks, tick = 1 milliSecs
      Scope   Ticks        %  Source
    $shell$       6    22.2%  |prompt:///|(10,23,<1,10>,<1,33>)
      crawl       6    22.2%  |std:///util/FileSystem.rsc|(481,1,<17,73>,<17,74>)
      crawl       4    14.8%  |std:///util/FileSystem.rsc|(495,1,<17,87>,<17,88>)
isDirectory       3    11.1%  |std:///util/FileSystem.rsc|(446,1,<17,38>,<17,39>)
      crawl       2     7.4%  |std:///util/FileSystem.rsc|(465,8,<17,57>,<17,65>)
      crawl       2     7.4%  |std:///util/FileSystem.rsc|(471,1,<17,63>,<17,64>)
      crawl       1     3.7%  |std:///util/FileSystem.rsc|(408,90,<17,0>,<17,90>)
      crawl       1     3.7%  |std:///util/FileSystem.rsc|(464,22,<17,56>,<17,78>)
    $shell$       1     3.7%  |prompt:///|(0,35,<1,0>,<1,35>)
      crawl       1     3.7%  |std:///util/FileSystem.rsc|(434,63,<17,26>,<17,89>)

rascal>crawl(|project://smallsql|);
FRAMES PROFILE: 6 data points, 157 ticks, tick = 1 milliSecs
  Scope   Ticks        %  Source
  crawl     156    99.4%  |std:///util/FileSystem.rsc|(408,90,<17,0>,<17,90>)

ASTS PROFILE: 6 data points, 157 ticks, tick = 1 milliSecs
      Scope   Ticks        %  Source
isDirectory     126    80.3%  |std:///util/FileSystem.rsc|(446,1,<17,38>,<17,39>)
      crawl      15     9.6%  |std:///util/FileSystem.rsc|(481,1,<17,73>,<17,74>)
      crawl       8     5.1%  |std:///util/FileSystem.rsc|(495,1,<17,87>,<17,88>)
      crawl       5     3.2%  |std:///util/FileSystem.rsc|(471,1,<17,63>,<17,64>)
      crawl       2     1.3%  |std:///util/FileSystem.rsc|(408,90,<17,0>,<17,90>)
```

On Windows:

```
rascal>crawl(|home:///Downloads/smallsql0.21_src|)
FRAMES PROFILE: 6 data points, 58 ticks, tick = 1 milliSecs
 Scope   Ticks        %  Source
crawl      58   100.0%  |std:///util/FileSystem.rsc|(408,90,<17,0>,<17,90>)

ASTS PROFILE: 6 data points, 58 ticks, tick = 1 milliSecs
      Scope   Ticks        %  Source
      crawl      25    43.1%  |std:///util/FileSystem.rsc|(495,1,<17,87>,<17,88>)
isDirectory      22    37.9%  |std:///util/FileSystem.rsc|(446,1,<17,38>,<17,39>)
      crawl       4     6.9%  |std:///util/FileSystem.rsc|(481,1,<17,73>,<17,74>)
      crawl       4     6.9%  |std:///util/FileSystem.rsc|(471,1,<17,63>,<17,64>)
      crawl       2     3.4%  |std:///util/FileSystem.rsc|(465,8,<17,57>,<17,65>)
      crawl       1     1.7%  |std:///util/FileSystem.rsc|(408,90,<17,0>,<17,90>)

rascal>crawl(|project://smallsql0.21_src|)
FRAMES PROFILE: 7 data points, 161 ticks, tick = 1 milliSecs
  Scope   Ticks        %  Source
  crawl     160    99.4%  |std:///util/FileSystem.rsc|(408,90,<17,0>,<17,90>)

ASTS PROFILE: 7 data points, 161 ticks, tick = 1 milliSecs
      Scope   Ticks        %  Source
isDirectory      97    60.2%  |std:///util/FileSystem.rsc|(446,1,<17,38>,<17,39>)
      crawl      41    25.5%  |std:///util/FileSystem.rsc|(495,1,<17,87>,<17,88>)
      crawl      11     6.8%  |std:///util/FileSystem.rsc|(481,1,<17,73>,<17,74>)
      crawl       9     5.6%  |std:///util/FileSystem.rsc|(471,1,<17,63>,<17,64>)
```

So some timings:

|  | project | file |
|---|---:|---:|
| linux | 157ms | 27ms |
| windows | 161ms | 58ms |

So there is still a factor, but not nearly as big as you are seeing @aleandromifsud .

**Comment by aleandromifsud** [comment]
@DavyLandman I ran it again and it is indeed much faster now! it's a huge upgrade, thank you for the support!

![image](https://user-images.githubusercontent.com/23127859/199339420-0c49f5d3-cac9-4b39-bbd1-a7656a6acf5c.png)
![image](https://user-images.githubusercontent.com/23127859/199339477-18f41a8e-ce6f-45c6-a018-cdf3ddeeacfb.png)

**Comment by DavyLandman** [comment]
So I'm gonna close this now, I don't see many more options to improve this, without adding some caching around the project resolution. That would be nice, but would require some two way communication to invalidate those caches predictably.

**Comment by jurgenvinju** [comment]
Great work both! 

> That parameter was only used inside that single class, for that specific api. I understand your concern, so maybe we 
> should do something more generic, but I did check if this class was used outside of the scope of resolving project paths. 
> (Offsets etc are always dropped for this operation)

That's ok then. Thanks for checking. Let's add some Javadoc to make sure people don't start reusing this class for other things. There are other places in the protocol where we communicate source locations as parameters, so there is some duplication going on that we might be tempted to factor out in the future.

**Comment by DavyLandman** [comment]
> That's ok then. Thanks for checking. Let's add some Javadoc to make sure people don't start reusing this class for other things. There are other places in the protocol where we communicate source locations as parameters, so there is some duplication going on that we might be tempted to factor out in the future.

Due to the low costs, I've added the fields in there, offsets etc won't be supported, but that's okay.
