### ISSUE TITLE
IDEServices::showDocument troubles

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/rascal-language-servers#208]
**Describe the bug**

* [ ] can not jump to logical locations
* [ ] can not deal with offset/length, line/column information

This has an effect on the effectivitity of  vis::Basic, vis::Charts and vis::Graphs, which all three use the IDEServices::edit function which maps to the IDEServices interface method showDocument

**Comment by DavyLandman** [comment]
@jurgenvinju I think you spend time making this ready right?

**Comment by jurgenvinju** [comment]
This was fixed
