### ISSUE TITLE
Bracket highlighting highlights wrong brackets when a bracket is escaped as part of a pattern

### ISSUE THREAD

**Issue by JJWTimmer** [usethesource/rascal-language-servers#214]
**Describe the bug**
I think this belongs in this repo, correct me if I'm wrong.
Bracket highlighting highlights wrong brackets when a bracket is escaped as part of a pattern. See screenshot.

**To Reproduce**

In VSCode create a .rsc file and paste something along the following lines:
```rascal
module bug::Report

void dummy(/include::\{LibDir\}<path:[^\]]+>\[tags=module\]/) {}
```

**Expected behavior**
The escaped bracket should have a different color from the outer bracket. In the screenshot you see the red bracket should be blue, and the escaped one should be red.

**Screenshots**
![image](https://user-images.githubusercontent.com/609540/207140182-8d2f2814-dfa6-4a7f-8625-c206f9e264f1.png)

**Stack traces**

**Desktop (please complete the following information):**
Windows, VSCode + JDK 11

**Comment by jurgenvinju** [comment]
Yep. I think we use the default language agnostic bracket matcher; so it doesn't know about escapes. Correct me if I'm wrong. Would be good to fix for DSLs as well.

**Comment by DavyLandman** [comment]
True, it's a new feature in vs code. We'll have to update the language
config.

**Comment by DavyLandman** [comment]
Details about the feature: https://code.visualstudio.com/blogs/2021/09/29/bracket-pair-colorization (it appears to use the syntax highlighting to find out if something is inside a string or not.

This file will need some new love: https://code.visualstudio.com/api/language-extensions/language-configuration-guide

And here some details of the interaction of the feature with the syntax highlighting of the language: https://code.visualstudio.com/updates/v1_67#_bracket-pair-colorization-enabled-by-default

**Comment by jurgenvinju** [comment]
can we register these things dynamically per extension too? for DSLs? The interface is very similar to the way Eclipse IMP used to solve this BTW.

**Comment by DavyLandman** [comment]
nope, these seem to be static, sadly.

**Comment by DavyLandman** [comment]
We cannot solve this issue, it's a limitation of the VS Code language configuration, it doesn't support escaping chars.
