### ISSUE TITLE
Parse errors in modules sometimes reported without position information

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/rascal-language-servers#216]
**Describe the bug**

<img width="695" alt="image" src="https://user-images.githubusercontent.com/1990295/208067978-9c1623be-0b07-4e9c-ba66-25ad42f0d82e.png">

rather unhelpful, especially in large files.

**Comment by DavyLandman** [comment]
Can you check the output window which offsets were there?

Since it looks like we are reporting parse error with offset (at the first
keyword).

**Comment by jurgenvinju** [comment]
> at file:///Users/jurgenv/git/rascal-tutor/src/lang/rascal/tutor/Indexer.rsc offset=10399 length=0 begin=208:6 end=208:6

**Comment by jurgenvinju** [comment]
Notably line `208` is the last line of the file.

**Comment by jurgenvinju** [comment]
The fact that the first word is selected in the visible could perhaps be an artifact of the completion feature?

**Comment by jurgenvinju** [comment]
Am also a bit surprised that completion comes in as a factor in this trace. I did not select any auto-complete short-cut or something.

**Comment by jurgenvinju** [comment]
This was fixed by fixing https://github.com/usethesource/rascal/issues/1736
