### ISSUE TITLE
Module lang::rascal::lsp::outline could not be imported

### ISSUE THREAD

**Issue by Eike14** [usethesource/rascal-language-servers#217]
**Describe the bug**

I want to reproduce a project based on this extensions in vs code. If I click on any rascal file, I get a lot of error messages that the module lang::rascal::lsp::outline could not be imported.

**To Reproduce**

1. Download the small project here [https://zenodo.org/record/7211893](url) and unzip it
2. Download the Rascal Metaprogramming Language extension in VS Code. I used the newest version 0.6, but it also did not work with version 0.5
3. Add the unzipped folder to the workspace
4. Open the src/ArtifactSLE22 file
5. Then the errors should be visible in the output

**Expected behavior**
No errors should appear and if I click on the link on the top of the file I could open the rascal terminal and setup the project

**Screenshots**

![error2](https://user-images.githubusercontent.com/16037110/208308928-a91850fc-4d50-4bce-b4d3-f9f7b4eff3c4.png)

**Stack traces**
![gradual-grammars-artifact-sle-2022_errors](https://user-images.githubusercontent.com/16037110/208308789-693f6bb7-cc66-4d34-b0de-a1c5e2b9ca6b.jpg)

**Desktop (please complete the following information):**
 - Context: VSCode
 - RascalVersion 0.6 and 0.5

**Comment by DavyLandman** [comment]
First off, this is not a specific error for that project, this looks like an error in your rascal installation. (as it's the rascal-outline that fails to load, not the DSL outline that the module might define).

Could you share some more details:
- os
- java version
- vscode version

Also, once you are past that hurdle, I think the project is missing a `pom.xml`. Newer versions of the vscode plugin require a correct maven file to resolve dependencies. Maybe @tvdstorm can help with that?

**Comment by Eike14** [comment]
Thank you for your answer,
I used the following versions:
Windows 11
Java 11 
VSCode 1.74

Okay, the problem is that i am not used to rascal. Maybe it is an option to install an earlier version of the extension?

**Comment by DavyLandman** [comment]
Okay, if you could share the whole output window, that would help a lot.

Just select all the lines, copy and paste it in here.

(Maybe as an attachment on the GitHub issue)


Based on that we should be able to figure out what is happening.

**Comment by Eike14** [comment]
Yeah sure I will attend a txt file with the complete error message. Thank you very much.

[errorMessage.txt](https://github.com/usethesource/rascal-language-servers/files/10257553/errorMessage.txt)

**Comment by DavyLandman** [comment]
> Yeah sure I will attend a txt file with the complete error message. Thank you very much.
> 
> [errorMessage.txt](https://github.com/usethesource/rascal-language-servers/files/10257553/errorMessage.txt)

The output window should contain a lot more messages, if you can, scroll all the way to the top.

**Comment by Eike14** [comment]
Unfortunately not as you can see here:

![errorMessage](https://user-images.githubusercontent.com/16037110/208383550-7250aa42-f3a3-4677-8f80-9ba7057604e6.png)

**Comment by DavyLandman** [comment]
Can you restart vscode? I think this can only happen if you click the "clear output".

**Comment by Eike14** [comment]
Oh yeah now it is longer
[errorMessage.txt](https://github.com/usethesource/rascal-language-servers/files/10257671/errorMessage.txt)

**Comment by DavyLandman** [comment]
Thank you, that helped. I think I know what is happening.

```
INFO: resolved |lib://rascal-lsp| at |jar+file:///C:/Users/Eike%2520Idczak/.vscode/extensions/usethesource.rascalmpl-0.6.0/assets/jars/rascal-lsp.jar!/|
```

I think there is a path problem we haven't encountered before. Your username get's encoded as `Eike%2520Idczak`. Most likely we decode that incorreclty. I assume your username contains non-ascii characters?

Sorry if that's the case, we have to make sure this works correctly.

As a workaround, you can start vscode with a custom ` --extensions-dir=c:\vscode-extentions` to see if that solves it.

**Comment by Eike14** [comment]
Yeah my username contains a space. Maybe I should change that if that can cause a problem. I will try it out.

**Comment by DavyLandman** [comment]
better not go metting around with user names ;)

indeed, start a terminal and write

```
code --extensions-dir=c:\temp\extensions
```

**Comment by Eike14** [comment]
Yeah now it worked perfectly. Thank you very very much.

**Comment by DavyLandman** [comment]
We've fixed it, leaving this open until we make a new release that contains that fix.

**Comment by DavyLandman** [comment]
Latest release (v0.6.1) includes these fixes.
