### ISSUE TITLE
Protect rascal commands only intended for code-lenses from regular user invocation.

### ISSUE THREAD

**Issue by djswagerman** [usethesource/rascal-language-servers#220]
The option “Start Rascal Terminal and import this module”, gives the error “Command 'Start Rascal Terminal and Import this module' resulted in an error (command 'rascalmpl.importMain' not found)”.

1. Open empty folder
2. Create folder src/demo
3. Create file 'hello.rsc' in this folder with the following content:
  module demo::basic::Hello
  import IO;
  
  void hello() {
     println("Hello world, this is my second Rascal program!");
  }
4. Type CMD+SHIFT+P and choose option "Start Rascal Terminal and import this module"

This create the error

**Expected behavior**
A rascal terminal should be opened with the module module demo::basic::Hello imported and ready to use.

**Screenshots**

<img width="261" alt="Screenshot 2023-01-03 at 12 26 45" src="https://user-images.githubusercontent.com/155615/210348486-01a4abbe-0daf-4424-a6a4-140cbb2ed555.png">

**Stack traces**
Toggle developer option did not result in any additional information.

**Desktop (please complete the following information):**
 - Visual Studio code Version: 1.74.2
 - Rascal plugin version v0.6.0
 - Mac Ventura
 - Apple M1 Max
 - JDK Temurin 11
 

**Additional context**

**Comment by DavyLandman** [comment]
This command should not be run via `cmd+shift+p`. **We should detect this happening and give a better message**. Normally you should see a small code-lens pop-up above the main method. As follows:

![image](https://user-images.githubusercontent.com/179603/210522934-3456aea1-b613-452d-aa34-36dd51b33038.png)

Clicking any of these is the desired interaction of this command.

**Comment by DavyLandman** [comment]
@yami2200 fixed this in #279
