### ISSUE TITLE
Clair in visual studio code: Could not import module lang::c::AST

### ISSUE THREAD

**Issue by djswagerman** [usethesource/rascal-language-servers#221]
**Describe the bug**

After following work instruction https://github.com/usethesource/clair clair is loaded, but not added to the search path. Executing import lang::c::AST in the rascal shell gives the error Could not import module lang::c::AST: can not find in search path

**To Reproduce**

1. Follow instructions at  https://github.com/usethesource/clair
2. Start a rascal shell
3. Execute 
`import lang::c::AST`
4. Now the error appears:
`Could not import module lang::c::AST: can not find in search path`

**Expected behavior**
After following the clair work instructions for visual studio code, Module 'lang::c::AST' should be imported

**Screenshots**
-
**Stack traces**
-

**Desktop (please complete the following information):**
- Visual Studio code Version: 1.74.2
- Rascal plugin version v0.6.0
- Mac Ventura
- Apple M1 Max
- JDK Temurin 11

**Additional context**

**Comment by DavyLandman** [comment]
I think @rodinaarssen helped out with this one? Can we sumarize what went wrong and what we could learn (i.e. where do we need to make this process smoother?)

**Comment by rodinaarssen** [comment]
This has been solved indeed. The key points were:
* The project needed a valid `pom.xml` (with a dependency on `clair` 0.6.2)
* The project needed a `Require-libraries` dependency on `|lib://clair|` in `META-INF/RASCAL.MF`
* The Rascal REPL needs to be started while having a Rascal module of the client project open/active
* `lang::c::AST` does not exist; `lang::cpp::AST` should be imported instead

**Comment by DavyLandman** [comment]
Thanks for solving it, so point 1 and 2 might be something for the clair readme? While maybe we should try and make the project context more clear for REPLs?

**Comment by rodinaarssen** [comment]
Points 1 and 2 are not specific to ClaiR; configuring dependencies should be documented in the Rascal documentation.

Indeed, maybe we can get the project name to appear somewhere in the REPL?

**Comment by DavyLandman** [comment]
> Points 1 and 2 are not specific to ClaiR; configuring dependencies should be documented in the Rascal documentation.

True, @jurgenvinju is writing it out.

Yet, many projects list their copy-and-pasteable dependency section. As an end-user I always like if I can just copy and paste the command (or pom section) for this specific library.

**Comment by rodinaarssen** [comment]
Fair enough

**Comment by jurgenvinju** [comment]
The rascal tutor will generate the copy-paste section of pom.xml automatically in the main page of each "package".
