### ISSUE TITLE
Automatic download failed:  Error: unexpected response Not Found

### ISSUE THREAD

**Issue by djswagerman** [usethesource/rascal-language-servers#226]
**Describe the bug**

Automatically downloading Java 11, results in an error "Automatic download failed:  Error: unexpected response Not Found" in rascal plugin version v0.6.2, 17 Jan 2023

**To Reproduce**
1) Removed /Library/Java/JavaVirtualMachines/temurin-11.jdk     
2) Removed Visual Studio Code
3) Reinstalled Visual Studio Code
4) Dialog box appears:
-> Rascal (or a DSL that uses Rascal) requires at least Java 11 runtime (max 17). Shall we download it, or will you set it up yourself?
5) Chose 'Automatically download...'
6) Accepted GPL license
7) Selected Eclipse Tumerin
8) Error ccures

**Expected behavior**
Eclipse Tumerin is downloaded to /Library/Java/JavaVirtualMachines/temurin-11.jdk 

**Screenshots**
![image](https://user-images.githubusercontent.com/155615/213874273-d2339cc6-a135-4a7d-bc67-235502b9ef10.png)

**Stack traces**
See screenshot

**Desktop (please complete the following information):**
- Apple M1 Max
- Ventura 13.1
- Visual Studio Code:
    Version: 1.74.3 (Universal)
    Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
    Date: 2023-01-09T17:07:18.579Z (1 wk ago)
    Electron: 19.1.8
    Chromium: 102.0.5005.167
    Node.js: 16.14.2
    V8: 10.2.154.15-electron.0
    OS: Darwin arm64 22.2.0
    Sandboxed: No
- Rascal plugin version v0.6.2

**Additional context**

**Comment by DavyLandman** [comment]
It looks like this is something where temurin is not releasing all builds at the same time:

https://github.com/adoptium/adoptium/issues/202

Mac aarch64 is not released for the latest build (`11.0.18+10`) yet. So we have to see if we can detect that in the API and take better care of this construction of the right version to download.

**Comment by zdtsw** [comment]
there are two parts of the release 
1) API will be first available to download tarball etc
2) later,mac pkg, linux rpm etc will be available to download from different repositories. (except widdows msi)

this could be an hour to days delay from 1) to 2)

**Comment by DavyLandman** [comment]
hi @zdtsw,

thanks for helping out. 

Currently we are using `https://api.adoptium.net/v3/info/release_versions` like this:
https://github.com/usethesource/rascal-language-servers/blob/bf3c3a9a52ec80e3a1ed1ba4caf61ac520286589/rascal-vscode-extension/src/auto-jvm/downloaders.ts#L167

To get the latest version, and then we use that to request the right binary from this endpoint: `https://api.adoptium.net/v3/binary/version/`.

Is there an endpoint (or set of parameters) that could help us determine the most recent _available_ version of a specific architecture? Such that for example mac-aarch64  get 11.0.17 while linux-x64 gets 11.0.18.

**Comment by zdtsw** [comment]
> hi @zdtsw,
> 
> thanks for helping out.
> 
> Currently we are using `https://api.adoptium.net/v3/info/release_versions` like this:
> 
> https://github.com/usethesource/rascal-language-servers/blob/bf3c3a9a52ec80e3a1ed1ba4caf61ac520286589/rascal-vscode-extension/src/auto-jvm/downloaders.ts#L167
> 
> To get the latest version, and then we use that to request the right binary from this endpoint: `https://api.adoptium.net/v3/binary/version/`.
> 
> Is there an endpoint (or set of parameters) that could help us determine the most recent _available_ version of a specific architecture? Such that for example mac-aarch64 get 11.0.17 while linux-x64 gets 11.0.18.

i suspect that you did not set the query on os and architecture which can lead to different return.
if you use https://api.adoptium.net/q/swagger-ui/#/Release%20Info/getReleaseVersions and "try it out"

**Comment by DavyLandman** [comment]
🤦🏼 I should have seen those arguments. Thanks!
