### ISSUE TITLE
Consider publishing rascalmpl extension to Open-VSX

### ISSUE THREAD

**Issue by Animajosser** [usethesource/rascal-language-servers#233]
**Is your feature request related to a problem? Please describe.**
I am using the open source version of VS Code. Third party builds are not allowed to use the Visual Studio Marketplace and therefore I use Open-VSX. However rascalmpl doesn't seem to be available on Open VSX (https://open-vsx.org/?search=rascal). I now have to download the .vsix file from the Visual Studio Marketplace website, build it myself or install an illegal extension to use the Visual Studio Marketplace anyway.

**Describe the solution you'd like**
Could you publish the extension on Open VSX (https://open-vsx.org)?

**Comment by jurgenvinju** [comment]
Thanks for the suggestion. @davylandman let's have a look at this. the more imho the merrier if we can automate the deployment with github actions.

**Comment by DavyLandman** [comment]
if you setup an account (and sign the right things), I'll take a look at automation side.

**Comment by jurgenvinju** [comment]
* already had the right account with the Eclipse organization
* OPEN_VSX_ACCESS is the name of the access token in the github usethesource organization
* created a "namespace": "usethesource" to host our extension in
* uploaded vsix version 0.6.3 for good measure manually to populate the namespace (it officially does not exist until it has at least one member according to the docs)
* claimed the namespace via an issue here, following the docs: <https://github.com/EclipseFdn/open-vsx.org/issues/1613>

**Comment by jurgenvinju** [comment]
HI @DavyLandman can you have a look at this? gitpod only works with openvsx or explicit URLs, and my confusion between those two has already led to weird effects. If we simply have the latest extension on both marketplaces, the confusion is gone.

**Comment by jurgenvinju** [comment]
we could trigger this one a debug tag for now and remove the deploy manually after that? a release is not something we want to do without all of the testing.

**Comment by jurgenvinju** [comment]
I mean a tag regex that we can use to test the deploy script to openvsx only. Like `test-openvsx-[0-9]*` or something.
