### ISSUE TITLE
Project name suddenly uncapitalized at unknown location

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/rascal-language-servers#244]
**Describe the bug**

Somewhere between summary construction and declaration resolution (for jump-to-def) I have `project://CapitalName` being renamed to `project://capitalName` which wreaks havoc on the editor features.

The bug is not in typepal. It happens purely when the summary is computed from the TModel and requested by the LSP and then used by the LSP.

**Comment by jurgenvinju** [comment]
Ok it happens only after the "definition" message arrives at the client, still with the correct capitalization.

**Comment by jurgenvinju** [comment]
Current hypothesis:
* URI is converted somewhere to a URL
* authority becomes a hostname because of that
* hostname is canonicalized to lowercase
* URL is either converted back to URI or used to open the editor directly

This would explain the behavior. Now looking for the proof.

**Comment by jurgenvinju** [comment]
Ok. it's both worse and better than expected. `vscode.Uri` implements RFC 3986 (the URI standard), which says this:

<https://www.rfc-editor.org/rfc/rfc3986#page-38:~:text=6.2.2.1.%20%20Case%20Normalization>

> [6.2.2.1](https://www.rfc-editor.org/rfc/rfc3986#section-6.2.2.1).  Case Normalization
> For all URIs, the hexadecimal digits within a percent-encoding
> triplet (e.g., "%3a" versus "%3A") are case-insensitive and therefore
>   should be normalized to use uppercase letters for the digits A-F.
>
>   When a URI uses components of the generic syntax, the component
>   syntax equivalence rules always apply; namely, that the scheme and
>   host are case-insensitive and therefore should be normalized to
>   lowercase.  For example, the URI <HTTP://www.EXAMPLE.com/> is
>   equivalent to <http://www.example.com/>.  The other generic syntax
>   components are assumed to be case-sensitive unless specifically
>   defined otherwise by the scheme (see [Section 6.2.3](https://www.rfc-editor.org/rfc/rfc3986#section-6.2.3)).

Apparently `java.util.URI` does _not_ implement this part of the RFC, while `vscode.Uri` _does_.

Since all project URI go through the VFS system with our own VFS providers, they all must go through the `vscode.Uri` representation and thus both the schemes and the authorities are normalized to lowercase.

**Comment by jurgenvinju** [comment]
* workaround: add an error/warning in the IDE for projects with non-lowercase names
* fix: vallang the `IValueFactory.sourceLocation(*)` methods should implement paragraph 6.2.2.1 of RFC3986
* fix: `java.net.URI` can be fixed, since we use that below ISourceLocation instances.

**Comment by jurgenvinju** [comment]
update: `java.net.URI` implements a different RFC for URIs: [RFC 2396](https://www.ietf.org/rfc/rfc2396.txt)

Because, why have only one standard if you can have more? I'm frustrated.

**Comment by DavyLandman** [comment]
If you look at `URIUtil` we already fix stuff around strange implementation of java's URI implementation. I think (but this is long ago) there was also an issue on how it dealt with non ascii paths. so making the authority path not case-sensitive would be a solution.

But, beware, this might break rascal on case-sensitive file systems. as `project://X` would point to `$WORKSPACEPATH/X` which is not the same as `project://x` on linux and mac.

**Comment by jurgenvinju** [comment]
It's breaking now exactly because of this and exactly in that manner.

For now, I think the safest short-term solution is to warn users about capital letters in their project names.

And it makes sense to start removing all capitals from schema names if we have them. I recall `PATH` being the only one. Could be wrong. 

When we fuse URIUtil into ISourceLocation and IValueFactory, we could consider normalizing the scheme and authorities to lowercase, and we'd have to re-implement the project scheme's many implementations to cover for accidental capital letters in folders and project names.
