### ISSUE TITLE
Warn users about non-lowercase non-dash characters in their project names

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/rascal-language-servers#252]
This is the cause of #244 which seems to have to solution at the root cause of it. So we need to help the user.

**Comment by DavyLandman** [comment]
Maybe the RASCAL.MF validator can include this check?

**Comment by jurgenvinju** [comment]
Yes makes sense. And the project generator(s); one of which I just adapted.

**Comment by DavyLandman** [comment]
Fixed in #255
