### ISSUE TITLE
VSCode show content panel customization

### ISSUE THREAD

**Issue by tbolwerk** [usethesource/rascal-language-servers#256]
**Is your feature request related to a problem? Please describe.**
The enum for setting up the vscode panel for show content panel is hardcoded to be ViewColumn.One, if this is customizable I could implement much more user friendly interfaces, by clicking on an visual element go to the side panel instead of replacing the visualization with a textual one. 

**Describe the solution you'd like**
[Link to the function signature that should be changed](https://github.com/usethesource/rascal-language-servers/blob/main/rascal-vscode-extension/src/lsp/RascalLSPConnection.ts#L73)

add an optional parameter that sets the enum: vscode.ViewColumn.One e.g. I want to add or change this to vscode.ViewColumn.Beside.

**Describe alternatives you've considered**
Change the code myself.

**Additional context**

**Comment by DavyLandman** [comment]
Hi @tbolwerk, which way are you invoking this? via `browse`? In that case it would require changes to rascal as well, as it all flows from there.

It might be a nice compact change, do you want to try and pick this up and turn it into a PR?

**Comment by jurgenvinju** [comment]
In particular the interactions with setMonitor on the evaluator context have a design flaw and should be treated carefully.

**Comment by jurgenvinju** [comment]
This is being fixed in #286 as we speak

**Comment by jurgenvinju** [comment]
done. 

* IDEServices::browse and IDEServices::showInteractiveContent now have the additional keyword parameters `title` and `viewColumn` which will be used by the IDE to label the tab and pick the right viewColumn. A viewColumn of `-1` leads to the last used viewColumn. 
* The two constructors for interactive and non-interactive `Content` in the `Content` module have the same parameters. The terminal will call the IDEServices automatically setting the respective parameters as specified.
