### ISSUE TITLE
Show "static errors" from the Rascal code running in the LSP server execution as errors in the Problem View and Annotations in the editor rather than a OUTPUT log entry.

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/rascal-language-servers#257]
**Describe the bug**

If we have a problem in the contribution callback code that is registered with a language, and 
a static error is throw, then this error is buried in the OUTPUT log rather than brought to the attention
of the meta programmer. This can be perceived as magic.

**To Reproduce**

Make a bug in the Pico summary code; run it. See it appearing in the OUTPUT log but nowhere else.

**Comment by jurgenvinju** [comment]
The problem is that even though the language is registered in the terminal, it is loaded in another JVM instance (that runs the parametrized DSL LSP server). 

It would be quite a workaround/hack to send the log information back from the parametrized LSP instance, to the VScode client, then back to the terminal that connects to it. Or another route would be from the LSP instance to the VScode client, to the Rascal LSP instance, over the terminal connection....  For one thing, there could be many terminals that are running and we do not even have an address mechanism for those terminals.

No. Although printing in the terminal would be optimal for the user, I don't think I want to maintain that solution. Let's just print the errors in a clear log file. If possible we could have an OUTPUT tab _per_ registered language, rather than only one for all DSLs. For now, let's log our warnings in the OUTPUT tab of the parametric DSL.

**Comment by DavyLandman** [comment]
We could register a new output view in VS Code per registered language? and just log the output of the evaluator to that view?

**Comment by DavyLandman** [comment]
This has been solved in #388
