### ISSUE TITLE
Hover help in Rascal file displays seemingly random data

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/rascal-language-servers#260]
**Describe the bug**

<img width="740" alt="image" src="https://github.com/usethesource/rascal-language-servers/assets/1990295/6afa054c-66c9-4f05-a1e4-5d00517aa433">

This shows the hover help of a "randomly" different constructor. This is not due to the previous dirty summary bug, this
one is always random.

**Comment by jurgenvinju** [comment]
`cose()` was never mentioned near this code.

**Comment by DavyLandman** [comment]
I see it 2 lines up.

**Comment by jurgenvinju** [comment]
So unless a summary is _never_ updated at all after the first time, I don't see how it could be that stable. Could it be that?

**Comment by jurgenvinju** [comment]
You know what this smells of? @memo function caches.

**Comment by jurgenvinju** [comment]
<img width="491" alt="image" src="https://github.com/usethesource/rascal-language-servers/assets/1990295/02fa3894-dff6-4f35-affa-8e23f0a8a3ae">

Now it's `bool` all the time..

**Comment by jurgenvinju** [comment]
I see it running clearly in the progress view too

**Comment by DavyLandman** [comment]
> I see it running clearly in the progress view too

that doesn't mean it also succeeded successfully. Sometimes we gone and messed up some kind of final step. But that is mostly visible with complete missing output, not just some kind of stuck values.

Would be interesting to see what the TModel for the file was (and if we could make it to a smaller test case, so we could inspect the output manually)

**Comment by DavyLandman** [comment]
Ok, found multiple bugs in the code:

1. rascal-core was giving types for modules that wasn't requested, but we were just putting them all (with offsets of the original module) in the current module
2. rascal-core always defines the type of the whole function. this means overlapping ranges, the underlying datastructure does not deal with that correctly.
3. there was a bug with overlapping ranges, that would keep only one of the overlapping ranges, with a random key / value pair (custom operator bug)

1 and 3 I've fixed, number 2 is a lot more annoying.
