### ISSUE TITLE
Pico demo does not have documentation strings (@synopsis, @description, @benefits, @pitfalls)

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/rascal-language-servers#270]
A minimal explanation would go a long way in making newcomers comfortable with the LanguageServer API.

**Comment by jurgenvinju** [comment]
The documentation is online here: https://www.rascal-mpl.org/docs/Packages/RascalLsp/API/demo/lang/pico/LanguageServer/

**Comment by DavyLandman** [comment]
This has been completed now.
