### ISSUE TITLE
show editor for rascal source location value (including jumping to the right point in the file)

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/rascal-language-servers#28]
This requires communicating the contents of a source location to the IDE, instead of the other way around..

**Comment by jurgenvinju** [comment]
several other features depend on this, including being able to follow references into a library and hyperlinking in the terminal to source locations.

**Comment by jurgenvinju** [comment]
* https://code.visualstudio.com/api/extension-guides/custom-editors
* https://github.com/microsoft/vscode-extension-samples/blob/main/custom-editor-sample/src/pawDrawEditor.ts

**Comment by DavyLandman** [comment]
The hyperlink in the terminal work, so it's now only a concern for the IDE features that are triggered from Rascal side.

**Comment by DavyLandman** [comment]
This has been implemented a while back, we had to make rascal VFS available in VS Code.
