### ISSUE TITLE
Unicode characters are getting mangled in the REPL

### ISSUE THREAD

**Issue by DavyLandman** [usethesource/rascal-language-servers#326]
**Describe the bug**

I've noticed that unicode characters are getting mangled, it's visible when you use `prettyTree` but also in other cases.

in the VS Code REPL if you type in this:

```
rascal>"\U01F4A9"
str: "?"
---
?
---
rascal>print("\U01F4A9")
≡ƒÆ⌐ok
rascal>"\u251C"
str: "├"
---
├
---
rascal>println("\u251C")
Γö£
ok
```

We get 2 different renderings of the same string.

and if we do it in a seperate terminal window (but with the same jar):

```
rascal>"\U01F4A9"
str: "💩"
---
💩
---
rascal>print("\U01F4A9")
💩ok
rascal>"\u251C"
str: "├"
---
├
---
rascal>println("\u251C")
├
ok
```

Strangely, for some smaller unicode chars (that fit in the lower plain), the string result printing goes okay, but calling print on that string fails.

**Expected behavior**
Correct printing of unicode chars

**Desktop (please complete the following information):**
 - Context: VS Code Extesion REPL on windows.
 - Rascal Version: 0.33.7 rascal on 0.9.1 vs code

**Additional context**
I've looked at linux, and there it's okay. Have no mac to verify this on.

**Comment by DavyLandman** [comment]
It looks like the `print` function is outputting utf8 chars (since `├` is 3 utf8 bytes, and `💩` is 4 utf8 bytes) but those are not interpreted as utf8 bytes but, but in as 3 different characters in some code page/encoding. Also this behavior is different than how the result values are printed to the repl, and different how in linux it's encoded.

**Comment by jurgenvinju** [comment]
I don't have this issue on my mac.

**Comment by jurgenvinju** [comment]
It's probably an effect of configuration in the context. What is your TERM variable saying?
