### ISSUE TITLE
Provide a clear error message when project is configured incorrectly in VS Code

### ISSUE THREAD

**Issue by PieterOlivier** [usethesource/rascal-language-servers#330]
When a new user does not follow the correct project initialization procedure (as explained in https://www.rascal-mpl.org/docs/GettingStarted/CreateNewProject/), the Rascal extension seems to work at first.
But when you click on "Import in new Rascal terminal" nothing happens and no error message is shown.

To help a new user getting started, it would help a lot if a clear error message was displayed in this case.

Also, for a user who installed Rascal by installing the Rascal VS Code extension, it is not clear how to run the Rascal REPL to follow the steps in https://www.rascal-mpl.org/docs/GettingStarted/CreateNewProject/.
The location of `rascal-<version>.jar` (as referred to in https://www.rascal-mpl.org/docs/GettingStarted/RunningRascal/) is hard to find in this case.

**Comment by jurgenvinju** [comment]
Both improve the docs and improve the error messages. I think if we put the error in the file on the module name this would help.

**Comment by DavyLandman** [comment]
I think if you click "import in terminal" we should try and detect common problems as well.

**Comment by jurgenvinju** [comment]
I like this feature, but it is yet more typescript code while we could also have solved this in pure Rascal. Let's merge it for now, but I'd like to see a missing project setup reported as an error in the module, and as a lense command to help fix it. Both could be a part of the Rascal code for the LSP implementation.

**Comment by DavyLandman** [comment]
I assume this was a comment on the PR?

**Comment by jurgenvinju** [comment]
Yes. I'd like to see these features implemented in Rascal. There is a growing collection of typescript code that is not easily ported to other IDEs. In general, a strategy could be to implement anything on the other side of the LSP where possible, in the interest of portability.
