### ISSUE TITLE
VS Code extension gets confused if default Java version is set incorrectly

### ISSUE THREAD

**Issue by linuswagner** [usethesource/rascal-language-servers#332]
We were on a system running OpenJDK 8 and 11.
OpenJDK 8 was set as the default.

When you install the VS Code extension in this context, it does not prompt you with the dialog if you want to install a JDK.

However, the REPL fails to load, because it tries the default version of the JDK (here: 8) and his is below the supported version of Rascal.

Either, the plugin should notify the user of this problem and help to change the default or Rascal itself should not go for the system default, but for the JDK that it supports.

**Comment by DavyLandman** [comment]
Strange, that should not have been allowed, as the regex detects that `javac 1.8.0_342` as jdk8.

**Comment by DavyLandman** [comment]
I just tested it out on a fresh install of windows, installed java 8, and on first start of a REPL (or any other rascal action), I get this popup:

![image](https://github.com/usethesource/rascal-language-servers/assets/179603/25363518-f861-49b3-8fa6-eb6f77d2e227)

after that, it installs the local version of java and it works. maybe it's different on ubuntu?

**Comment by jurgenvinju** [comment]
Thanks @linuswagner  for reporting and the thoughtful analysis. Cheers!

**Comment by DavyLandman** [comment]
> However, I found that VS Code does not prompt during a single session again if you click the message away.
> Only, if you close and re-open VS Code, the popup comes again.

this is by design, to not bother the user too much. but then again, stuff isn't working as they would expect (as in there is no rascal). So maybe we should reconsider this.

But like Jurgen said, thanks for verifying.
