### ISSUE TITLE
Report all exceptions to LSP via `ResponseErrorException` instead of generic exception, which don't reach VS Code with any detail.s

### ISSUE THREAD

**Issue by DavyLandman** [usethesource/rascal-language-servers#384]
**Is your feature request related to a problem? Please describe.**
Most of exceptions/errors that rascals throws are hidden in the output window, but LSP has an dedicated `error` field for this. If we translate them to this, VS Code can decide how/if to report errors.

**Describe the solution you'd like**
Add something so that most of our futures get a special handler to wrap exceptions with `ResponseErrorException`.

**Describe alternatives you've considered**
Leave as is, with the downside that users are less updated in case of something goes wrong.

**Additional context**

**Comment by jurgenvinju** [comment]
oooo that would be very nice. Much easier debugging.
