### ISSUE TITLE
Can not start terminal to generate pom.xml file if a a pom.xml file is missing

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/rascal-language-servers#435]
**Describe the bug**

<img width="348" alt="image" src="https://github.com/user-attachments/assets/97d56287-a077-4d1b-848a-5adde10e5322">

There is a project setup generator function in the documentation that users can call, but if I press "OK" the terminal does not start.

**Comment by DavyLandman** [comment]
Hmm, that is an interesting catch-22.

**Comment by jurgenvinju** [comment]
The terminal will work fine without a pom. Perhaps we can start the generic terminal (no project settings).

Also we talked on the phone to add a "quick-fix" to this situation such that a correct pom.xml can be generated automatically. @DavyLandman  Shall we turn that into a separate issue?

**Comment by DavyLandman** [comment]
sounds good to me.

**Comment by DavyLandman** [comment]
![image](https://github.com/user-attachments/assets/0d2ccd36-ce90-4023-bfe5-55ef994639ee)


Where possible, I've replace the `ok` button with the text: "Still start the REPL", and when a users presses this, the repl will be started, but the user has been warned it might be janky.
