### ISSUE TITLE
false positive warning about library files not being well-supported

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/rascal-language-servers#479]
<img width="969" alt="image" src="https://github.com/user-attachments/assets/9b1feade-c17f-43e8-b35f-1c264ddcea8c">

**Comment by jurgenvinju** [comment]
This happens for all standard library modules, and also for well-configured dependencies in other libraries.

**Comment by PaulKlint** [comment]
I have also seen this and had no idea what it meant, whether this was harmful or what to do about it.

Question 1: who generates this and why?

**Comment by jurgenvinju** [comment]
If you open a file outside of the srcs folders in the pathconfig then editor features like the static checker don't work well. The rascal lsp server checks this and produces the error.

I think it doesn't consider files in library folders that have .tpl files. Because these are also well supported by the LSP server.

**Comment by DavyLandman** [comment]
We got to improve this heuristic to not fire for library files that are openend, as we have special support for them.

Also, we discussed that missing pom.xml files see #443 and #434 should be fined tuned a bit more.
