### ISSUE TITLE
Always fold the @license tag

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/rascal-language-servers#488]
**Is your feature request related to a problem? Please describe.**

The first 26 lines of all our Rascal files contain the license header which is always the same and it is uninformative in 99.99% of the reasons for reading a module. On my laptop that is 80% of the editor's real estate.

**Describe the solution you'd like**

The `@license` tag already folds on demand. Perhaps it to be folded by default.

**Comment by DavyLandman** [comment]
I've just checked the [foldingRange](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#foldingRange) result of LSP, and there is no way to communicate we want to have a certain region of code folded.

I've also looked at the [VS Code API](https://code.visualstudio.com/api/references/vscode-api), and it has no concept of prefolding a region, and also no API to programmatically fold certain regions.

So I think we cannot solve this in VS Code. Please re-open if you've seen an API that would fit this use case.

I think we could consider pointing towards the license file?

**Comment by DavyLandman** [comment]
@PaulKlint are you okay with opening a separate issue and closing this one?
