### ISSUE TITLE
terminal link resolver does not work for logical URI

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/rascal-language-servers#74]
Even when the M3 model is registered using analysis::m3::Registry, clicking on the logical links of an M3 model does nothing, while clicking on the physical source links works fine.

**Comment by jurgenvinju** [comment]
I've added the feature to resolve URI against the Rascal LSP's URIResolverRegistry instance. This makes logical URI's work that are present in all instances of JVMs (such as home:/// and tmp:///) but it does not work for logical URIs that registered dynamically, such as the resolved names of code entities in M3 models.

Either we resolve this at registration time somehow, or we query the terminal instance for the information at run-time.

**Comment by jurgenvinju** [comment]
At the moment we do not have a binary communication socket with the terminal. Adding that is possible but also adds more coupling to a system that is already too tightly coupled imo.

**Comment by jurgenvinju** [comment]
changing the implementation and design of registering logical resolvers has big impact on the rascal project. also not ideal..

**Comment by jurgenvinju** [comment]
The only solution I see currently is the to add `registerLogicalScheme` to the IDEServices, and thread the implementation of registerLogicalScheme java method in the `analysis::m3::Registry` module through that interface. 

* In that way the terminal IDEServices can forward the registration to both the local registry and the remote LSP registry
* The standard implementation of IDEServices would then have to simply register with the local registry
* Making analysis::m3::Registry dependent on IDEServices is "ok" since all its uses used to come from the Eclipse context anyway... (this is a guess)
* If there is code running analysis::m3::Registry in a context without IDEServices (only IRascalMonitor) present, it would start crashing at module load time with an exception (no IDEServices available) from the JavaBridge

**Comment by jurgenvinju** [comment]
This would be an extension of #68

**Comment by DavyLandman** [comment]
> At the moment we do not have a binary communication socket with the terminal. Adding that is possible but also adds more coupling to a system that is already too tightly coupled imo.

We can always (like the virtual file system is already doing) encode bytes using base64 strings? Or is there a different reason you would like a 'binary communication'?

**Comment by DavyLandman** [comment]
The rest of your ideas I cannot oversee the implications, could you specify a bit more what is the exact problem and the tradeoff for your solution?

Or is this just a issue to keep track of your progress so you wont forget? In that case, I won't try to understand and provide feedback.

**Comment by jurgenvinju** [comment]
I miswrote "binary"; I mean two-way

**Comment by jurgenvinju** [comment]
I don't have an alternative, so no trade-off to think about yet. My current thinking is that IDEServices needs extending anyway by #68 so another method with that would not hurt. 

Implementing #68 is a lot of work because there are now four implementations of the IDEServices interface, one of which communicates from the terminal to the LSP via its own socket interface. So for those messages I've to come up with POJO classes to send over all the stuff to the other side. 

That's probably going to be solved in the same way we did earlier with the Base64 encodings of large vallang values.

Anyway, I'm now doing all the preparing work for that on the `rascal` project side, and I think Monday the rest on the rascal-lsp side. By both terminal and LSP code can:
* (un)register new logical locations
* (un)register new diagnostics using the `Message` format
* log errors/warnings/info also using the `Message` format
* show errors/warnings/info to the user, also using the `Message` format

So that is 6 new methods to the IDEServices interface.

Later in Eclipse IDE and terminal shell we can reuse these methods instead of implementing our own stuff. This will all help to lower the total amount of code we write for IDE support, eventually. Currently it just adds to it.

**Comment by jurgenvinju** [comment]
Fixed only the logical URIs and scaffolded all the other IDEServices; ready for a slamdunk on Monday :-)
