### ISSUE TITLE
type-checker can not import from local modules

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/rascal-language-servers#80]
![image](https://user-images.githubusercontent.com/1990295/134314416-c6347c15-facf-4fbd-b16e-b083121a7f74.png)

**Comment by rodinaarssen** [comment]
Observation: it appears that the type checker bails out if one import cannot be resolved. This is "too early", and leads to all then-unresolved assets being reported as errors

**Comment by jurgenvinju** [comment]
I've assigned @PaulKlint ; if this is the case then we could migrate this issue to the rascal project.

**Comment by jurgenvinju** [comment]
This may have been caused by:
* usethesource/rascal#1556 , or
* usethesource/rascal#1557

which both have been solved in the meantime.So let's wait until we merge #125 because that also upgrades us into a version of `rascal-core` that includes fixes to these above two issues.

**Comment by DavyLandman** [comment]
This has been fixed, luckily.
