### ISSUE TITLE
Being able to browse the libraries a project depends on (like `std:///`)

### ISSUE THREAD

**Issue by jurgenvinju** [usethesource/rascal-language-servers#93]
Rascal-eclipse offers the feature of browsing a libraries we depend on in the tree view to the left.
It is something @tvdstorm and I use a lot, and we would like something like that in VScode. 

This includes
the "Show in" feature of the editor, where you could jump from the library file in an editor (for example you'd end up there while debugging or following a declaration reference), to the library file in the tree view.

It's worth investigating what the idiomatic manner for exploring libraries is in VScode/LSP before we start
replicating exactly how Eclipse did it. 

It is also worth investigating how to visualize/make browsable the _full information_ of a PathConfig instance for a project. This includes not only the roots of all libraries, but also other configuration options which are good to make transparant such as the `bin` folder and JVM `classpath`. As often things go wrong around classpaths and libraries, it is very good to be able to see what is going on after the paths have been resolved.

**Comment by DavyLandman** [comment]
We could make a special tree view that exposes it? They are not that hard to make, and you can choose what to expose there.

It's a pity the file explorer doesn't support virtual file systems *yet*.

**Comment by DavyLandman** [comment]
If you look at node/typescript, the project dit always includes `node_modules` and other languages often have include paths that point to real files on disk.

Currently we support a user is jumping to a definition, since we've exposed `std` and friends to VS Code.

**Comment by jurgenvinju** [comment]
yes some tree view sounds good. In Eclipse I made a tree view that would accept any Rascal node value and would use the keyword field names for labels. For directory location values it would create a folder, and then for files it would have clickable entries with the name and extension as labels. 

If we re-create that then if something changes to PathConfig the tree-view code does not need to be adapted...

**Comment by jurgenvinju** [comment]
Also if some DSLs add more fields to the PathConfig type, they would immediately be supported.
